version: '3.7'

volumes:
  pi_share: {}

services:
  rpishare:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pishare
    image: pishare:latest
    ports:
      - 137:137/tcp
      - 137:137/udp
      - 138:138/tcp
      - 138:138/udp
      - 139:139
      - 445:445
      - 445:445/udp
    hostname: rpi-samba
    volumes:
      - pi_share:/share/data
      - /usr/share/zoneinfo/Europe/Berlin:/etc/localtime
    command: -u "${USERNAME:-user}:${PASSWORD:-password}" -s "pishare:/share/data:rw:${USERNAME:-user}"
    restart: unless-stopped
